export const PEDESTAL_FLOOR_SIZE = 5.5
export const PEDESTAL_FLOOR_TOP_Y = -0.02
export const PEDESTAL_FLOOR_THICKNESS = 0.12
export const PEDESTAL_FLOOR_CENTER_Y = PEDESTAL_FLOOR_TOP_Y - PEDESTAL_FLOOR_THICKNESS / 2
export const PEDESTAL_FLOOR_HALF_EXTENTS: [number, number, number] = [
  PEDESTAL_FLOOR_SIZE / 2,
  PEDESTAL_FLOOR_THICKNESS / 2,
  PEDESTAL_FLOOR_SIZE / 2,
]

export const PEDESTAL_FLOOR_COLOR = '#b9b1a5'
export const PEDESTAL_FLOOR_FRICTION = 0.94
export const PEDESTAL_FLOOR_RESTITUTION = 0.01
