export const pwaManifest = {
  id: '/',
  name: 'CAILLOU™',
  short_name: 'CAILLOU™',
  description: 'Une présence minérale de qualité.',
  lang: 'fr',
  dir: 'ltr',
  start_url: '/',
  scope: '/',
  display: 'standalone',
  orientation: 'any',
  background_color: '#f2efe9',
  theme_color: '#f2efe9',
  categories: ['lifestyle', 'entertainment'],
  prefer_related_applications: false,
  icons: [
    {
      src: '/icons/pwa-192x192-provisional.png',
      sizes: '192x192',
      type: 'image/png',
      purpose: 'any maskable',
    },
    {
      src: '/icons/pwa-512x512-provisional.png',
      sizes: '512x512',
      type: 'image/png',
      purpose: 'any maskable',
    },
  ],
} as const
